name: walltext
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  gap: ^3.0.1

  #state
  provider: ^6.1.2

  #caching
  shared_preferences: ^2.3.2
  flutter_cache_manager: ^3.4.1


  image: ^4.2.0
  http: ^1.2.2
  path_provider: ^2.1.4
  
  #permission
  permission_handler: ^11.3.1
  
  #wallpaper
  flutter_wallpaper_manager: ^0.0.4
  image_picker: ^1.1.2
  device_info_plus: ^10.1.2
  flutter_native_splash: ^2.4.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


# Splash Screen Settings
flutter_native_splash:
  color: "#737373" # Arka plan rengi
  image: assets/icon/wall_text_ic.png # Splash görüntüsü
  android_12:
    image: assets/icon/wall_text_ic.png # Android 12+ için splash görüntüsü
    color: "#737373" # Arka plan rengi

    
flutter:
  uses-material-design: true
  assets:
  - assets/icon/wall_text_ic.png


