name: wallpaper_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  image: ^4.2.0
  http: ^1.2.2
  path_provider: ^2.1.4
  flutter_wallpaper_manager: ^0.0.4
  flutter_cache_manager: ^3.4.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/IMG_20240622_134627.jpg


